### PR TITLE
Do not start candidate pair check if already started

### PR DESCRIPTION
**Pull request by eerimoq**
Not sure if it is a bug or not, but it seems odd that `check_start()` is potentially called multiple times for the same candidate pair. I've seen log entries that shows state transitions such as `IN_PROGRESS -> IN_PROGRESS`, and `SUCCESS -> SUCCESS`. Such state transitions does not occur with this fix.

### CODE REVIEW

**Comment by jlaine** [comment]
For the transition from `SUCCEEDED` to `SUCCEEDED` you are probably right. AFAICT the only place a pair gets transitioned to this state is when `check_start()` completes, so it does look like an indication that `check_start()` is running more than once for a given air.

As for the "bogus" transitions you are seeing from `IN_PROGRESS` to `IN_PROGRESS`, I think this might be something else. This could occur when retrying a check following a role conflict. You'll notice that in that case, `check_start() ` will call itself.

**Comment by eerimoq** [comment]
Here is a complete log. I added a "reason" string at the end of the state transition log entries to make it clear why the state was set.

Looks like the reason for `IN_PROGRESS -> IN_PROGRESS` is that the first check was triggered by an incoming message, and then a second time by highest priority. Should be enough to do one of those checks? That's at least what this PR is intended to fix.

```
2023-02-01 21:34:45,709 aioice.ice stun/dgram Connection(1) protocol(4) rx ('192.168.50.72', 61301) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf3\x12\xc1\x9b\xa3\x18)*\x05&5q')
2023-02-01 21:34:45,709 aioice.ice stun/dgram Connection(1) protocol(4) tx ('192.168.50.72', 61301) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xf3\x12\xc1\x9b\xa3\x18)*\x05&5q')
2023-02-01 21:34:45,744 aioice.ice Connection(1) Discovered peer reflexive candidate Candidate(Hir2hI51Pa 1 udp 1853817087 192.168.50.72 61301 typ prflx)
2023-02-01 21:34:45,744 aioice.ice Connection(1) Check CandidatePair(('192.168.50.181', 45132) -> ('192.168.50.72', 61301)) State.WAITING -> State.IN_PROGRESS (triggered by incoming)
2023-02-01 21:34:45,744 aioice.ice stun/dgram Connection(1) protocol(4) tx ('192.168.50.72', 61301) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'K\xa1|\x8fy\xf3\x9blrH\x8av')
2023-02-01 21:34:45,745 aioice.ice Connection(1) Check CandidatePair(('192.168.50.181', 45132) -> ('192.168.50.72', 61301)) State.IN_PROGRESS -> State.IN_PROGRESS (highest priority waiting)
2023-02-01 21:34:45,745 aioice.ice stun/dgram Connection(1) protocol(4) tx ('192.168.50.72', 61301) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x14\xed\xdd\x81\xd0\xc4b\xf7\xeb\xa2\xe3\xc0')
2023-02-01 21:34:45,749 aioice.ice stun/dgram Connection(1) protocol(4) rx ('192.168.50.72', 61301) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'K\xa1|\x8fy\xf3\x9blrH\x8av')
2023-02-01 21:34:45,749 aioice.ice Connection(1) Check CandidatePair(('192.168.50.181', 45132) -> ('192.168.50.72', 61301)) State.IN_PROGRESS -> State.SUCCEEDED (success)
2023-02-01 21:34:45,749 aioice.ice Connection(1) ICE completed
2023-02-01 21:34:45,750 aioice.ice stun/dgram Connection(1) protocol(4) rx ('192.168.50.72', 61301) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\x14\xed\xdd\x81\xd0\xc4b\xf7\xeb\xa2\xe3\xc0')
2023-02-01 21:34:45,750 aioice.ice Connection(1) Check CandidatePair(('192.168.50.181', 45132) -> ('192.168.50.72', 61301)) State.SUCCEEDED -> State.SUCCEEDED (success)
```

**Comment by eerimoq** [comment]
You are probably busy, but sending a reminder that this is still open.

**Comment by jlaine** [comment]
> You are probably busy, but sending a reminder that this is still open.

I'm now convinced your change is correct. I have slightly altered the name of the wrapper method, and rebased it to account for the switch from `ensure_future` to `create_task`, and will be merging it once CI completes.

**Comment by jlaine** [comment]
Thanks for your work and your patience, I've released version 0.9.0 with this PR.

**Pull request merged**
