### PR TITLE
Make Connection.add_remote_candidate a coroutine

### PR DESCRIPTION
**Pull request by jlaine**
Also, remove the Connection.remote_candidates setter.

### CODE REVIEW

**Comment by marksteward** [comment]
I haven't checked how Chrome does it, but I'm not sure it's best to resolve "in-line" when adding a candidate. If DNS is slow to resolve, this has the effect of slowing the acceptance of inbound connections until DNS times out. Wouldn't it be better to use the DNS name in the candidates and do resolution async after connect()?

Happy to check other implementations tomorrow.

**Comment by jlaine** [comment]
Hi @marksteward ! Thanks for the feedback, this is indeed a point I've been wondering about.

My test case for this is using `aiortc`'s `server` example with the following changes: disabling audio by default and invoking `start()` upon loading the page:

```patch
index 18ff33b..6486475 100644
--- a/examples/server/index.html
+++ b/examples/server/index.html
@@ -39,7 +39,7 @@
     </select>
 </div>
 <div class="option">
-    <input id="use-audio" checked="checked" type="checkbox"/>
+    <input id="use-audio" type="checkbox"/>
     <label for="use-audio">Use audio</label>
     <select id="audio-codec">
         <option value="default" selected>Default codecs</option>
@@ -108,5 +108,6 @@
 <pre id="answer-sdp"></pre>
 
 <script src="client.js"></script>
+<script>start()</script>
 </body>
 </html>
```

In my tests I'm receiving two mDNS candidates, one which resolves successfully and one which does not. I'm seeing the kind of behaviour you describe, namely a hold up due to the second lookup timing out.

There are two things which make me hesitate to defer resolving the mDNS candidates:

- do we want to make `add_remote_candidate` raise an exception, in order for the caller to know whether a candidate was accepted or rejected? We can only do this if we immediately perform the lookup.

- we need to pair remote candidates with our local candidates. We can only do this once we figure out whether we're dealing with an IPv4 or IPv6 address. Deferring the mDNS lookup means also deferring candidate pairing and I'm a bit afraid of what this will mean in terms of complexity.

**Comment by marksteward** [comment]
Looks like Chrome keeps the hostname along with the candidate, and accepts invalid ones just fine, adding them to `remoteDescription.sdp`. It does an asynchronous name resolve for any that end with `.local`, even before createAnswer() has been called, and silently ignores any that don't resolve.

If you wanted to do the same, `add_remote_candidate` could silently ignore invalid candidates, but candidates would need some sort of resolution callback/event after which they can start trying to send data. I'd be happy to have a go at this if you think it's worth it.

That said, `addIceCandidate` is async in Javascript, so it makes sense to make this change anyway. And it'll be great to have mDNS working at some level!

**Comment by stalkerg** [comment]
Why this PR was closed?

**Comment by marksteward** [comment]
> Why this PR was closed?

It looks like changing the branch from master to main closed all PRs...

**Comment by stalkerg** [comment]
> It looks like changing the branch from master to main closed all PRs...

ahhh it was a bad idea...

**Comment by marksteward** [comment]
I mean Github has a feature explicitly for doing this, so it's not a bad idea, just looks like something went wrong.

**Pull request closed without merging**
